apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-helloworld-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-helloworld
  strategy: {}
  template:
    metadata:
      labels:
        app: springboot-helloworld
    spec:
      containers:
      - image: techvault2024/springboot-helloworld:latest
        name: springboot-helloworld
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-helloworld-service
spec:
  selector:
    app: springboot-helloworld
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  